<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="139" started-at="2016-04-18T20:24:58Z" finished-at="2016-04-18T20:24:58Z">
    <groups>
      <group name="ui">
        <method signature="PalindromeTest.palindromeNegativeTest()[pri:0, instance:com.hpe.trainin.utils.tests.PalindromeTest@353e58cd]" name="palindromeNegativeTest" class="com.hpe.trainin.utils.tests.PalindromeTest"/>
      </group> <!-- ui -->
      <group name="api">
        <method signature="PalindromeTest.palindromePositiveTest()[pri:0, instance:com.hpe.trainin.utils.tests.PalindromeTest@353e58cd]" name="palindromePositiveTest" class="com.hpe.trainin.utils.tests.PalindromeTest"/>
      </group> <!-- api -->
      <group name="all">
        <method signature="PalindromeTest.palindromeNegativeTest()[pri:0, instance:com.hpe.trainin.utils.tests.PalindromeTest@353e58cd]" name="palindromeNegativeTest" class="com.hpe.trainin.utils.tests.PalindromeTest"/>
        <method signature="PalindromeTest.palindromePositiveTest()[pri:0, instance:com.hpe.trainin.utils.tests.PalindromeTest@353e58cd]" name="palindromePositiveTest" class="com.hpe.trainin.utils.tests.PalindromeTest"/>
      </group> <!-- all -->
    </groups>
    <test name="Default test" duration-ms="139" started-at="2016-04-18T20:24:58Z" finished-at="2016-04-18T20:24:58Z">
      <class name="com.hpe.trainin.utils.tests.PalindromeTest">
        <test-method status="PASS" signature="palindromeNegativeTest()[pri:0, instance:com.hpe.trainin.utils.tests.PalindromeTest@353e58cd]" test-instance-name="" name="palindromeNegativeTest" duration-ms="12" started-at="2016-04-18T13:24:58Z" finished-at="2016-04-18T13:24:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- palindromeNegativeTest -->
        <test-method status="FAIL" signature="palindromePositiveTest()[pri:0, instance:com.hpe.trainin.utils.tests.PalindromeTest@353e58cd]" test-instance-name="" name="palindromePositiveTest" duration-ms="96" started-at="2016-04-18T13:24:58Z" finished-at="2016-04-18T13:24:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.hpe.trainin.utils.tests.PalindromeTest.palindromePositiveTest(PalindromeTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- palindromePositiveTest -->
      </class> <!-- com.hpe.trainin.utils.tests.PalindromeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
